# ---- BUILD STAGE ----
FROM node:22.2.0-bullseye-slim AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# ---- RUN STAGE ----
FROM nginx:latest

# Copy build output
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port
EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]
